FROM harbor.airqualitychina.cn:2229/public/node:14.16.0-python3.7.2-alpine3.12 AS builder
WORKDIR /opt/web
COPY . ./

RUN npm config delete proxy \
  && npm config set registry http://registry.npmmirror.com/ \
  && npm install

ENV PATH="./node_modules/.bin:$PATH"

RUN npm run build
RUN sh bjmemc-dist-sed.sh

FROM nginx:1.21.6-alpine
RUN mkdir -p /data/deploy/bjmemc-electricity/ \
  && rm -f /etc/nginx/conf.d/default.conf

COPY ./nginx/nginx.conf /etc/nginx/conf/
COPY ./nginx/bjmemc-electricity.conf /etc/nginx/conf.d/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
COPY --from=builder /opt/web/dist /data/deploy/bjmemc-electricity/dist

